{
  description = "Unofficial, end-to-end encrypted CLI for Proton Mail, Drive, Calendar, Pass and Contacts";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs =
    { self, nixpkgs }:
    let
      systems = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-darwin"
        "x86_64-linux"
      ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});
      version = self.shortRev or self.dirtyShortRev or "dev";
    in
    {
      packages = forAllSystems (pkgs: {
        default = pkgs.buildGoModule {
          pname = "proton-cli";
          inherit version;

          __structuredAttrs = true;

          src = self;
          vendorHash = "sha256-mhzCAmQsuoMEgQKy7FQYnxoz9AHUCaSZoxejcRiJVjc=";

          subPackages = [ "cmd/proton" ];
          tags = [ "embed_hv" ];

          ldflags = [
            "-s"
            "-w"
            "-X=github.com/roman-16/proton-cli/internal/cli.version=${version}"
          ];

          nativeBuildInputs = [
            pkgs.installShellFiles
            pkgs.pkg-config
          ]
          ++ pkgs.lib.optionals pkgs.stdenv.hostPlatform.isLinux [ pkgs.wrapGAppsHook3 ];

          # glib-networking is the CAPTCHA webview's TLS: GIO loads it as a
          # module rather than having it built in, and nix has no ambient
          # libraries to supply one, so without it the window opens and says
          # "TLS support is not available".
          buildInputs = pkgs.lib.optionals pkgs.stdenv.hostPlatform.isLinux [
            pkgs.glib-networking
            pkgs.gtk3
            pkgs.webkitgtk_4_1
          ];

          # Builds the embedded CAPTCHA webview helper for the host platform,
          # matching the release binaries and the nixpkgs package.
          preBuild = ''
            bash scripts/build-hv-helpers.sh
          '';

          overrideModAttrs = _: {
            preBuild = null;
          };

          # The program is `proton`, with `proton-cli` beside it as a second
          # name. Fish autoloads a completion file named after the command
          # being typed, so the alias gets one that borrows the real one;
          # bash and zsh are told about both names by the script itself.
          postInstall = ''
            ln -s proton $out/bin/proton-cli
          ''
          # The completions are generated by running the binary that was just
          # built, which a build machine cannot do when it is not the host.
          + pkgs.lib.optionalString (pkgs.stdenv.buildPlatform.canExecute pkgs.stdenv.hostPlatform) ''
            installShellCompletion --cmd proton \
              --bash <($out/bin/proton completion bash) \
              --fish <($out/bin/proton completion fish) \
              --zsh  <($out/bin/proton completion zsh)
            installShellCompletion --cmd proton-cli \
              --bash <($out/bin/proton completion bash) \
              --fish <(echo 'complete -c proton-cli -w proton')
          '';

          meta = {
            description = "Unofficial, end-to-end encrypted CLI for Proton Mail, Drive, Calendar, Pass and Contacts";
            homepage = "https://github.com/roman-16/proton-cli";
            license = pkgs.lib.licenses.mit;
            mainProgram = "proton";
            platforms = pkgs.lib.platforms.linux ++ pkgs.lib.platforms.darwin;
          };
        };
      });

      apps = forAllSystems (pkgs: {
        default = {
          type = "app";
          program = "${self.packages.${pkgs.stdenv.hostPlatform.system}.default}/bin/proton";
          meta.description = "Unofficial CLI for Proton Mail, Drive, Calendar, Pass and Contacts";
        };
      });

      formatter = forAllSystems (pkgs: pkgs.nixfmt);
    };
}
