// @ts-check
import starlight from "@astrojs/starlight";
import { defineConfig, fontProviders } from "astro/config";
import starlightLinksValidator from "starlight-links-validator";
import starlightLlmsTxt from "starlight-llms-txt";
import starlightThemeBlack from "starlight-theme-black";

import { origin, repo } from "./site.ts";

export default defineConfig({
  fonts: [
    {
      cssVariable: "--font-inter",
      name: "Inter",
      provider: fontProviders.fontsource(),
    },
  ],
  integrations: [
    starlight({
      customCss: ["./src/styles/proton.css"],
      description:
        "Unofficial, end-to-end encrypted CLI for Proton Mail, Drive, Calendar, Pass and Contacts.",
      editLink: { baseUrl: `${repo}/edit/main/docs/` },
      /*
       * A command line is read, not scrolled. Wrapping keeps a long invocation
       * whole on a narrow screen, which is where most of them are met.
       *
       * A crontab has no grammar to highlight it with, and a schedule is five
       * fields and a command either way.
       */
      expressiveCode: {
        defaultProps: { wrap: true },
        shiki: { langAlias: { cron: "txt" } },
      },
      favicon: "/favicon.svg",
      lastUpdated: true,
      logo: { alt: "", src: "./src/assets/logo.svg" },
      plugins: [
        starlightThemeBlack({
          /*
           * A page here is a command line and a paragraph about it. Handing
           * either to somebody else's chat window is not what a reader came for,
           * and the control costs a button on every page to offer it.
           */
          docs: { showMarkdownActions: false },
          navLinks: [
            { label: "Docs", link: "/installation/" },
            { label: "Commands", link: "/commands/" },
          ],
        }),
        starlightLlmsTxt({
          description:
            "Unofficial, end-to-end encrypted CLI for Proton Mail, Drive, Calendar, Pass and Contacts. One binary, one grammar: proton <app> <collection> <verb>.",
          projectName: "proton-cli",
          /*
           * Somebody asking a model how to do something with this wants the
           * grammar before the catalogue: the shape is what makes the other two
           * hundred commands guessable, and the reference is what it then reads.
           */
          promote: ["index", "getting-started", "language", "output", "references"],
        }),
        starlightLinksValidator(),
      ],
      /*
       * The order is the order somebody meets the tool in: install it, learn the
       * sentence, then one page per app for the doing, then the exhaustive list
       * for the looking-up, then why any of it behaves the way it does.
       *
       * The command pages are listed rather than autogenerated because
       * autogeneration sorts them alphabetically, which puts the raw API above
       * Mail and Drive - the two the front page leads with.
       */
      sidebar: [
        {
          items: ["installation", "getting-started", "language"],
          label: "Start here",
        },
        {
          items: [
            "apps/mail",
            "apps/drive",
            "apps/calendar",
            "apps/pass",
            "apps/contacts",
            "apps/account",
            "apps/api",
          ],
          label: "The apps",
        },
        {
          items: ["scripting", "configuration"],
          label: "Automating it",
        },
        {
          items: [
            { label: "Commands", slug: "commands" },
            "commands/mail",
            "commands/drive",
            "commands/calendar",
            "commands/pass",
            "commands/contacts",
            "commands/account",
            "commands/api",
            "commands/self",
            "output",
            "references",
            "limitations",
          ],
          label: "Reference",
        },
        {
          items: ["how-it-works", "design-notes", "human-verification"],
          label: "Why it works this way",
        },
      ],
      social: [{ href: repo, icon: "github", label: "GitHub" }],
      title: "proton-cli",
    }),
  ],
  site: origin,
  trailingSlash: "always",
});
